apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cms.secretName" . }}
  labels:
    {{- include "cms.labels" . | nindent 4 }}
type: Opaque
stringData:
  sso-token: {{ .Values.secrets.ssoToken | quote }}
